name: Build and deploy SimpleRuleAiChatBotWeb to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
    steps:
      # Login to Azure using publish profile
      - name: Login to Azure Web App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      # Build the project using dotnet
      - name: Run Tests
        run: dotnet test --configuration Release
      
      # Publish the application to a specified folder
      - name: dotnet publish
        working-directory: ./SimpleBlazor
        run: dotnet publish -c Release -o ./output
        
      # Deploy the app to Azure Web App using the Azure Web Apps Deploy action
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          app-name: 'simpleai'
          slot-name: 'Production'
          package: './output'

